Refactor codebase into Typescript
pushex-project/pushex.js pull request #7
Opened 2020-07-24 21:21 UTC by raygesualdo

Steps taken to accomplish this:

- [x] Update testing and build tooling dependencies to latest versions
- [x] Add Typescript tooling dependencies
- [x] Convert JS files to TS and add type annotations
- [x] Add npm script to generate type files

2020-08-26 23:01 UTC, devproivansurzhenko requested changes

2020-08-26 23:44 UTC, raygesualdo commented on src/pushex.spec.js
> +      expect(sub.channel).toEqual(undefined)
Correct me if I'm wrong @sb8244, but I think Steve prefers `.toEqual` with the value over the other built-in methods.

2020-08-26 23:45 UTC, raygesualdo commented on src/pushex.ts
> +  ) {
You mean the constructor arguments type?

2020-08-27 00:18 UTC, devproivansurzhenko commented on src/pushex.ts
> +  ) {
Not just arguments. Something like that:

```
interface IPushexConfig {
  reconnectAlgorithm?: typeof DEFAULT_SOCKET_RECONNECT_ALGORITHM
  getParams?: () => Promise<Record<string, any>>
  onConnect?: (instance: Pushex) => void
  onConnectionError?: (instance: Pushex) => void
}

...

const DEFAULT_CONFIG = ...

...

export class Pushex {
  private config: IPushexConfig = DEFAULT_CONFIG

  constructor(url: string, config: IPushexConfig) {
    this.config = {...DEFAULT_CONFIG, ...config}
    ...
```

2020-08-27 02:38 UTC, raygesualdo commented on src/pushex.ts
> +  ) {
Yeah, I can could do that. Any preference @sb8244?

2020-09-07 02:20 UTC, sb8244 commented
I'm going to move this over to a typescript branch to finish off

2020-09-07 02:20 UTC, sb8244 commented
Looks greaT!!!

2020-09-07 02:20 UTC, merged

2020-09-07 02:23 UTC, sb8244 commented on src/pushex.spec.js
> +      expect(sub.channel).toEqual(undefined)
I prefer the toEqual functions.

2020-09-07 02:23 UTC, sb8244 commented on src/pushex.ts
> +  private getParams: () => Promise<Record<string, any>>
TIL about Record

2020-09-07 02:29 UTC, sb8244 commented on src/index.ts
> +export { SubscriptionFunction } from "./subscription"
nvm, things blow up 🙃

2020-09-07 02:30 UTC, sb8244 commented on src/pushex.ts
> +  ) {
Refactored to an interface. I handled the default a bit different though